language: python
env:
  global:
    secure: SnOb1gyjfP/qeo7ImKQU2nGyL+L253w426DdpXca2O0ar0u1RcKsy4lEq/Kl4yJtgguB/4LZmcq/+HCwTHWi0NHstOWu2HEdWBzFVbOX2xsMMSThQeOQVGzKQi9llbcikAGjIYvPXrcLD3bmEvA1V1iVGF/S70FKRFAEul7kfXFrhYcC5f8K8pw298tp9O1UHi2AGhRo4ly54OFVhSMD95+/C9OXWjBMMhgBM1H5x6a7Br+E8lZC9jmfb6hWSI93zd087FGTYSatq0TJ7Uy7zxJbnKQcSCfahEpREC8yvg7HQdScFtcV7tpCOe2VPNX/MYDdsYxr+hACw57qvb1PH8f+zWzA6TEK7pexDdJgn1/aF2+2mgqjMaY/Iz03+V9Ev2PkXZ0iHf2LrWIILO0uNv3tHJ+vMFAvJ0EgJHjX7dvTnpZm/swJRpmva7KVu90dBrgD7NG/uiYNCRBY1QAXbPV+lRN6lZ599G4x+3I77QjO7SIv9+odPXcDeOCnyhpp9nrajGscFwZQQwvPgcuQQtXIPVLtrpXpxZuhEj1zk1cJvwP8gS27M12v/VS24tfaaz9hYOKxRUzR1mkpU0pfzfHIbwloJ3SgyC7BeUZvqwM4mYU/0nALuSTMnmVMzzbOQkmEW9G3xFmO+8Jgi4CiCGgGKP90Pz9Fcr+c4NVJIfg=
install:
- pip install -e .
script:
- py.test
deploy:
  provider: pypi
  user: syncloud-build
  password:
    secure: efZQmglabqIie9TXO/KJFIymAZ7FE7u9TU2+dmIGkDkC9G62Np72QkhS7EFU/kzjcQGtLAj1SQxKCKKTzl/7v8CUOYJpUVNuEeeUvsnMuZqdMom5EJFgukqXiB2oyRZy4s8eI2BS4MfdTnUvOoM0MJH2WyeL5w/LhuzNj5P1VWzNi4FC6WbCMGl6tLcPGB/9ZX9Fd5fgJf2vpi7ZvU6b9RXDB83uOy3c3jNJPJ38PKDsOonWzBy/eC5/EItzHlFmBIna7mWGZKAlwrM7wTtEHwna/Wgv+ZX9qfhW6f11D88EdwXyMWOlp1eog4H8dHqLh+QpUc6v2tV/MpWo2t4k4bS8+UQaDWPuvESSXVDGH+5oAx/26itQQCxNKVcnSFb1yGrVGZsPpxXTILCdTEGaicbOZxF8lF3FnvMKcdshtkBxsIUoMiCURTkTeAr2ebzlJZmkzlVIEEt09mEm5jGLU0aG05pSkgffKxmHTbnQANB8kHb8QYH318PqJ8LXKrdN5YSxSWsZk+4MbvnVQ+r6hlSv4VLRVbV3RJaBvoWVdHYevgQkoePVuyiz9pF9fpfV03TnONdYh2k6zxpjOlu89H4ZJFAGj4HvEhf2VzbQ7fym82O69EDHpUh5L/BlrwXRgy6YSpQxPjTdrQF3YeLXRFRESVvLnl0MkgkeR6yDIrc=
after_deploy:
- pip install travis-tools
- version-increment version
- universal-version-push version ${TRAVIS_REPO_SLUG} syncloud-build GH_TOKEN ${TRAVIS_BRANCH} "Travis build [skip ci]"