#!/usr/bin/env python

import argparse
import os

from coinlib.debian import install_deb_package
from coinlib.python import install_python_package
from coinlib.raw import install_raw_package


def get_parser():
    argparser = argparse.ArgumentParser(description='Copy Installer')
    argparser.add_argument('--to', help='Output folder, current working directory by default', default=os.getcwd())
    argparser.add_argument('--cache_folder', help='Folder name used to store package in cache', default=None)
    argparser.add_argument('--ignore-cache', action='store_true')

    subparsers = argparser.add_subparsers(help='available commands', dest='action')

    sub = subparsers.add_parser('py', help="Install python package")
    sub.add_argument('url', help='Package url')

    sub = subparsers.add_parser('raw', help="Install raw archive")
    sub.add_argument('url', help='Archive url')
    sub.add_argument('--subfolder', help='Folder to put all contents of archive', default=None)
    sub.add_argument('--takefolder', help='Folder to take from archive', default=None)

    sub = subparsers.add_parser('deb', help="Install Debian package")
    sub.add_argument('url', help='Package url')
    sub.add_argument('--subfolder', help='Folder to put all contents of package', default=None)

    return argparser


if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()

    if args.action == 'py':
        install_python_package(args.cache_folder, args.url, args.ignore_cache, args.to)

    if args.action == 'raw':
        install_raw_package(args.cache_folder, args.url, args.ignore_cache, args.to, args.subfolder, args.takefolder)

    if args.action == 'deb':
        install_deb_package(args.cache_folder, args.url, args.ignore_cache, args.to, args.subfolder)
